name: Build and Deploy Code

on: [push, pull_request]

jobs:
  jobFastAPI:
    env:
      host: localhost
      password: Colesman1
      name: fastapi
      username: postgres
      SECRET_KEY: 89498gGD984Hn5gngNFNGFS4556fDGBHHERH54nfgDHJ879DHJe7EY7
      ALGORITHM: HS256
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2 
      - name: Installing python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Installing dependencies
        run: pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pytest