name: Build and Deploy Code

on: [push, pull_request]

jobs:
  jobFastAPI:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: Colesman1<
      DATABASE_NAME: fastapi
      DATABAsE_USERNAME: postgres
      SECRET_KEY: 89498gGD984Hn5gngNFNGFS4556fDGBHHERH54nfgDHJ879DHJe7EY7
      ALGORITHM: HS256  
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2 
      - name: Installing python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Installing dependencies
        run: pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pytest